rails__apt_packages: ['python-pip', 'python-dev', 'postgresql', 'nginx']
rails__dev_packages: ['postgresql-server-dev-all', 'zlib1g-dev']

rails_app_name: '{{ ansible_hostname }}'
postgres_db_name: '{{ rails_app_name }}'
postgres_db_user: '{{ rails_app_name }}'
postgres_db_password: '{{ rails_app_name }}'

rails_app_secret: "{{ rails_app_name|password_hash('sha512') }}"

postgres_users:
  - { name: '{{ postgres_db_user }}', password: '{{ postgres_db_password }}' }

# http_proxy: http://proxy.example.cz:3232/


ldap:
  enabled: false
  # domain: '{{ domain }}'
