rails__apt_packages: ['python-pip', 'python-dev', 'postgresql', 'nginx']
#zlib for nokogiri
rails__dev_packages: ['postgresql-server-dev-all', 'zlib1g-dev']

rails_app_name: '{{ ansible_hostname }}'
postgres_db_name: '{{ rails_app_name }}'
postgres_db_user: '{{ rails_app_name }}'
postgres_db_password: '{{ rails_app_name }}'

rails_app_secret: "{{ rails_app_name|password_hash('sha512') }}"

postgres_users:
  - { name: '{{ postgres_db_user }}', password: '{{ postgres_db_password }}' }

# http_proxy: http://proxy.example.cz:3232/


#rails__rack_env: production
# -------# EgovUtils settings #-------
# E-mail to send contact form to:
#rails__contact_mail: posta@resort.cz

ldap:
  enabled: False
  # domain: '{{ domain }}'

rails__sidekiq: False

# rails__ires:
#   url: "<ires webservice url>"
#   sign_cert_file: "<path to public certificate in pem>"
#   sign_cert_pkey_file: "<path to private key for certificate in pem>"
#   sign_cert_pkey_password: "<password for private key>"
