rails__apt_packages: ['python-pip', 'python-dev', 'postgresql', 'nginx']
rails__apt_additional_packages: []
#zlib for nokogiri
rails__dev_packages: ['postgresql-server-dev-all', 'zlib1g-dev', 'autoconf', 'autogen', 'libtool', 'libltdl-dev']

rails_app_name: '{{ ansible_hostname }}'
postgres_db_name: '{{ rails_app_name }}'
postgres_db_user: '{{ rails_app_name }}'
postgres_db_password: '{{ rails_app_name }}'

rails_app_secret: "{{ rails_app_name|password_hash('sha512') }}"

postgres_users:
  - { name: '{{ postgres_db_user }}', password: '{{ postgres_db_password }}' }

# http_proxy: http://proxy.example.cz:3232/

# User under whom the application server is running
rails__system_user: gitlab_deploy
# Folder where the application resides
rails__root_directory: "/srv/{{rails_app_name}}"
rails__working_directory: "{{rails__root_directory}}/current"

rails__rack_env: production

rails__reverse_proxy: False
rails__enable_ssl: False #expects cert and key in /etc/ssl/{certs,private}/nginx/{{rails_app_name}}.{crt,key}
rails_generate_certificate: True #allow to create the certificates

rails__kerberos: False #enables nginx kerberos for servis.justice.cz domains

# -------# EgovUtils settings #-------
# E-mail to send contact form to:
#rails__contact_mail: posta@resort.cz

ldap:
  enabled: False
  # domain: '{{ domain }}'

rails__ldap_additional_domains: []

rails__sidekiq: False
rails__sidekiq_queues:
  - name: default
    count: 2
  - name: mailers

external_apps:
  void_app: False
  # love_url: <url_to_loves>
  # ctd_url: <url_to_ctd>

# rails__ires:
#   url: "<ires webservice url>"
#   sign_cert_file: "<path to public certificate in pem>"
#   sign_cert_pkey_file: "<path to private key for certificate in pem>"
#   sign_cert_pkey_password: "<password for private key>"

# rails__redmine:
#   url: "<url for redmine change log>"
#   project_id: "<project_id in redmine>"
#   # OPTIONAL
#   # api_key: "<for non public projects define api key from redmine>"
#   # query_id: "<optional query_id>"
