- name: Install key for dotdeb
  apt_key:
    id: E9C74FEEA2098A6E
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present

- name: Add dotdeb deb server
  apt_repository:
    repo: deb http://ftp.utexas.edu/dotdeb/ stretch all

- name: Add dotdeb deb-src server
  apt_repository:
    repo: deb-src http://ftp.utexas.edu/dotdeb/ stretch all

- name: Install redis package
  apt:
    name: redis-server
    state: latest
    update_cache: yes

- name: Recomended redis configuration
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^appendonly'
    line: appendonly yes
  notify: restart redis

- name: Recomended redis configuration
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^appendfsync'
    line: appendfsync everysec
  notify: restart redis
