- name: Install key for dotdeb
  apt_key:
    id: E9C74FEEA2098A6E
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present

- name: Add dotdeb deb server
  apt_repository:
    repo: deb http://ftp.utexas.edu/dotdeb/ stretch all

- name: Add dotdeb deb-src server
  apt_repository:
    repo: deb-src http://ftp.utexas.edu/dotdeb/ stretch all

- name: Install redis package
  apt:
    name: redis-server
    state: latest
    update_cache: yes

- name: Recomended redis configuration
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^appendonly'
    line: appendonly yes
  notify: restart redis

- name: Recomended redis configuration
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^appendfsync'
    line: appendfsync everysec
  notify: restart redis

- name: Create sidekiq config file
  template:
    src: sidekiq_queues.yml.j2
    dest: /srv/{{rails_app_name}}/shared/config/sidekiq_queues.yml
    owner: gitlab_deploy
    group: gitlab_deploy

- name: Register sidekiq systemd service
  template:
    src: systemd/app-sidekiq.service.j2
    dest: /etc/systemd/system/{{rails_app_name}}-sidekiq.service
    owner: root
    group: root
    mode: 0644

- name: reload deamons for systemd and enable unicorn service
  systemd:
    daemon_reload: yes
    name: "{{rails_app_name}}-sidekiq"
    enabled: yes
